# Generated by Django 2.0.8 on 2018-08-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_1', '0006_auto_20180815_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
