# Generated by Django 2.0.8 on 2018-08-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_1', '0007_auto_20180815_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_publicacao',
            field=models.DateTimeField(blank=True),
        ),
    ]
